apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydocker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mydocker
  strategy: 
    rollingUpdate: 
      maxUnavailable: 0
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: mydocker        
    spec: 
      containers: 
        - 
          image: "akbardoc/redis"
          name: learning-demo
          ports: 
            - 
              containerPort: 8080
